export const LOADING = "LOADING";
export const FETCH_ALL = "FETCH_ALL";
export const OPEN_FAVOURITES = "OPEN_FAVOURITES";
export const CLOSE_FAVOURITES = "CLOSE_FAVOURITES";
export const ADD_FAVOURITE_MOVIE = "ADD_FAVOURITE_MOVIE";
export const REMOVE_FAVOURITE_MOVIE = "REMOVE_FAVOURITE_MOVIE";
export const CHANGE_BUTTON = "CHANGE_BUTTON";
